# Generated by Django 6.0.1 on 2026-01-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_location_id_user_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="자기소개"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender_visible",
            field=models.BooleanField(default=True, verbose_name="성별 공개"),
        ),
    ]
