# Generated by Django 6.0.2 on 2026-02-05 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='해시태그명')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
            ],
            options={
                'verbose_name': '해시태그',
                'verbose_name_plural': '해시태그',
                'db_table': 'Hashtag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('moim_date', models.DateField(verbose_name='모임 날짜')),
                ('moim_time', models.TimeField(verbose_name='모임 시간')),
                ('max_people', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='최대 인원')),
                ('is_closed', models.BooleanField(blank=True, default=False, null=True, verbose_name='모임 마감 여부')),
                ('is_cancelled', models.BooleanField(blank=True, default=False, null=True, verbose_name='폭파 여부')),
                ('moim_finished', models.BooleanField(blank=True, default=False, null=True, verbose_name='모집 완료 여부')),
                ('complete', models.BooleanField(blank=True, default=False, null=True, verbose_name='임시저장 여부')),
                ('gender_restriction', models.IntegerField(blank=True, choices=[(0, '누구나'), (1, '남성만'), (2, '여성만')], default=0, null=True, verbose_name='성별 제한')),
                ('age_restriction', models.IntegerField(blank=True, default=0, null=True, verbose_name='나이 제한')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('location', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='모임 장소')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'db_table': 'Post',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('APPROVED', '승인됨'), ('REJECTED', '거절됨'), ('CANCELLED', '취소'), ('COMPLETED', '완료')], default='PENDING', max_length=20, verbose_name='참여 상태')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='신청 시간')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='상태 변경 시간')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='승인 시간')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='moong.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '참여 상태',
                'verbose_name_plural': '참여 상태',
                'db_table': 'Participation',
                'ordering': ['create_time'],
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d/', verbose_name='이미지')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='moong.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '게시글 이미지',
                'verbose_name_plural': '게시글 이미지',
                'db_table': 'image',
                'ordering': ['order', 'create_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('is_author', models.BooleanField(blank=True, null=True, verbose_name='주최자 댓글 여부')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('author', models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='moong.comment', verbose_name='부모 댓글')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moong.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'Comment',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.ForeignKey(db_column='hashtag_id', on_delete=django.db.models.deletion.CASCADE, to='moong.hashtag', verbose_name='해시태그')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='moong.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '게시글-해시태그',
                'verbose_name_plural': '게시글-해시태그',
                'db_table': 'PostHashtag',
                'unique_together': {('post', 'hashtag')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', through='moong.PostHashtag', to='moong.hashtag', verbose_name='해시태그'),
        ),
        migrations.CreateModel(
            name='Ddomoong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('from_user', models.ForeignKey(db_column='from_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='given_ddomoongs', to=settings.AUTH_USER_MODEL)),
                ('participation', models.ForeignKey(db_column='participation_id', on_delete=django.db.models.deletion.CASCADE, related_name='ddomoongs', to='moong.participation')),
            ],
            options={
                'db_table': 'Ddomoong',
                'indexes': [models.Index(fields=['participation'], name='Ddomoong_partici_fd0b7c_idx'), models.Index(fields=['from_user'], name='Ddomoong_from_us_aea941_idx')],
                'unique_together': {('participation', 'from_user')},
            },
        ),
    ]
