# Generated by Django 6.0.1 on 2026-01-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moong", "0002_remove_post_location_id_post_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="save",
        ),
        migrations.AddField(
            model_name="post",
            name="complete",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="임시저장 여부"
            ),
        ),
    ]
