# Generated by Django 6.0.1 on 2026-01-26 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moong', '0002_remove_post_location_id_post_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d/', verbose_name='이미지')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='moong.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '게시글 이미지',
                'verbose_name_plural': '게시글 이미지',
                'db_table': 'image',
                'ordering': ['order', 'create_time'],
            },
        ),
    ]
