# Generated by Django 6.0.2 on 2026-02-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido', models.CharField(max_length=20)),
                ('sigungu', models.CharField(max_length=20)),
                ('eupmyeondong', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역',
                'db_table': 'location',
                'indexes': [models.Index(fields=['sido', 'sigungu', 'eupmyeondong'], name='location_sido_da206a_idx')],
                'unique_together': {('sido', 'sigungu', 'eupmyeondong')},
            },
        ),
    ]
